# Generated by Django 2.1 on 2018-10-24 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexPage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repo',
            name='lang',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
