# Generated by Django 2.1.2 on 2018-10-29 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexPage', '0002_auto_20181024_0558'),
    ]

    operations = [
        migrations.AddField(
            model_name='repo',
            name='picture',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
