# Generated by Django 2.1.2 on 2018-10-29 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexPage', '0003_repo_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repo',
            name='picture',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
